### ISSUE TITLE
Bug: not work on Ubuntu, need to use /etc/default/locale

### ISSUE THREAD

**Issue by laurent-kling** [robertdebock/ansible-role-locale#1]
### Bug

On Ubuntu, the config file is different.

Centos: `/etc/locale.conf`

```
- name: configure locale.conf centos
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
  notify:
    - localectl set-locale
```

Ubuntu: `/etc/default/locale`
https://www.thomas-krenn.com/en/wiki/Configure_Locales_in_Ubuntu

```
- name: configure locale.conf ubuntu
  template:
    src: locale.conf.j2
    dest: /etc/default/locale
  notify:
    - localectl set-locale
```
