### ISSUE TITLE
Undefined attributes in dict

### ISSUE THREAD

**Issue by Migsi** [robertdebock/ansible-role-locale#2]
## Describe the bug
To begin with, I'm unsure if this is a bug or just happens because I'm doing it wrong.

When trying to provision a remote Ubuntu LXC on a Proxmox Host, the role immediately fails with the error `fatal: [my.remote.host -> localhost]: FAILED! => {"msg": "'dict object' has no attribute 'password'"}`

## Playbook

I just paste the part of the playbook relating to locale(s), which is within our "common" role, as setting the locale is one of the things that needs to be done on all of our hosts.

```yaml
...
  # Locale role
- name: Change locale using external role
  include_role:
    name: robertdebock.locale
...
```
Our config done via group_vars/all.yml:

```yaml
...
# Default locale configuration
locale_lang: en_GB.UTF-8
locale_timezone: Europe/Vienna
...
```
Our requirements.yml which is fed into ansible before every run:

```yaml
roles:
  - name: robertdebock.bootstrap
    version: 5.2.3

  - name: robertdebock.locale
    version: 3.1.0
...
collections:
...
```

## Output

The first "TASK" in the output is the line calling the role, as described above.

```
...
TASK [Change locale using external role] **************************************************************************************************************************************************************************

TASK [robertdebock.locale : test if locale_lang is set correctly] *************************************************************************************************************************************************
fatal: [my.remote.host -> localhost]: FAILED! => {"msg": "'dict object' has no attribute 'password'"}
...
```

## Environment

- Control node OS: `NAME="Ubuntu" VERSION="20.04.3 LTS (Focal Fossa)"`
- Control node Ansible version: `ansible [core 2.11.3]`
- Managed node OS: `NAME="Ubuntu" VERSION="18.04.5 LTS (Bionic Beaver)"` actually just a LXC on a Proxmox 6.4-13 Host (Debian 10)

**Comment by robertdebock** [comment]
I think it has to do with your setup; the `password` attribute is not related to this role.

The error you are seeing comes from this code:

```yaml
- name: test if locale_lang is set correctly
  ansible.builtin.assert:
    that:
      - locale_lang is defined
      - locale_lang is string
    quiet: yes
```

Maybe just to be sure you can quote your values:

```yaml
locale_lang: "en_GB.UTF-8"
locale_timezone: "Europe/Vienna"
```

Although I don't really expect that to cause an issue.

Hope you find the issue, please reopen if you need further help.
