### ISSUE TITLE
Lack of idempotency on Debian

### ISSUE THREAD

**Issue by pandvan** [robertdebock/ansible-role-locale#8]
## Describe the bug

The role set the chosen locale(s) in `/etc/default/locale` surrounding them with double quotes.

```
cat /etc/default/locale
#
# Ansible managed
#

LANG="en_US.UTF-8"
```

On Debian distributions the handler then executes the command `update-locale LANG=en_US.UTF-8` that cause double quotes to be removed.

Maybe we could use `localectl` also on Debian 11, as it is shipped by `systemd` package.

## Playbook

```yaml
- hosts: all
  gather_facts: no
  become: no

  vars:
    # https://github.com/robertdebock/ansible-role-locale/blob/master/defaults/main.yml
    locale_timezone: Europe/Rome

  tasks:
    - ansible.builtin.setup:
        filter:
          - ansible_os_family
          - ansible_distribution

    - ansible.builtin.import_role:
        name: robertdebock.locale
```

## Output

Every execution after the first show this diff
```
--- before: /etc/default/locale
+++ after: /Users/_redacted_/.ansible/tmp/ansible-local-8260libc5m2z/tmpbk5uok4j/locale.conf.j2
@@ -1,4 +1,5 @@
 #
 # Ansible managed
 #
-LANG=en_US.UTF-8
+
+LANG="en_US.UTF-8"
```

## Environment

- Control node OS: MacOS 10.15
- Control node Ansible version: ansible-core 2.11.7
- Managed node OS: Debian 11
